# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/otserv/fortera/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/otserv/fortera/source/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/otserv/fortera/source/src/CMakeFiles /home/otserv/fortera/source/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/otserv/fortera/source/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tfs

# Build rule for target.
tfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tfs
.PHONY : tfs

# fast build rule for target.
tfs/fast:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/build
.PHONY : tfs/fast

actions.o: actions.cpp.o
.PHONY : actions.o

# target to build an object file
actions.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/actions.cpp.o
.PHONY : actions.cpp.o

actions.i: actions.cpp.i
.PHONY : actions.i

# target to preprocess a source file
actions.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/actions.cpp.i
.PHONY : actions.cpp.i

actions.s: actions.cpp.s
.PHONY : actions.s

# target to generate assembly for a file
actions.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/actions.cpp.s
.PHONY : actions.cpp.s

ban.o: ban.cpp.o
.PHONY : ban.o

# target to build an object file
ban.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ban.cpp.o
.PHONY : ban.cpp.o

ban.i: ban.cpp.i
.PHONY : ban.i

# target to preprocess a source file
ban.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ban.cpp.i
.PHONY : ban.cpp.i

ban.s: ban.cpp.s
.PHONY : ban.s

# target to generate assembly for a file
ban.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ban.cpp.s
.PHONY : ban.cpp.s

baseevents.o: baseevents.cpp.o
.PHONY : baseevents.o

# target to build an object file
baseevents.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/baseevents.cpp.o
.PHONY : baseevents.cpp.o

baseevents.i: baseevents.cpp.i
.PHONY : baseevents.i

# target to preprocess a source file
baseevents.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/baseevents.cpp.i
.PHONY : baseevents.cpp.i

baseevents.s: baseevents.cpp.s
.PHONY : baseevents.s

# target to generate assembly for a file
baseevents.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/baseevents.cpp.s
.PHONY : baseevents.cpp.s

bed.o: bed.cpp.o
.PHONY : bed.o

# target to build an object file
bed.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/bed.cpp.o
.PHONY : bed.cpp.o

bed.i: bed.cpp.i
.PHONY : bed.i

# target to preprocess a source file
bed.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/bed.cpp.i
.PHONY : bed.cpp.i

bed.s: bed.cpp.s
.PHONY : bed.s

# target to generate assembly for a file
bed.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/bed.cpp.s
.PHONY : bed.cpp.s

chat.o: chat.cpp.o
.PHONY : chat.o

# target to build an object file
chat.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/chat.cpp.o
.PHONY : chat.cpp.o

chat.i: chat.cpp.i
.PHONY : chat.i

# target to preprocess a source file
chat.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/chat.cpp.i
.PHONY : chat.cpp.i

chat.s: chat.cpp.s
.PHONY : chat.s

# target to generate assembly for a file
chat.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/chat.cpp.s
.PHONY : chat.cpp.s

combat.o: combat.cpp.o
.PHONY : combat.o

# target to build an object file
combat.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/combat.cpp.o
.PHONY : combat.cpp.o

combat.i: combat.cpp.i
.PHONY : combat.i

# target to preprocess a source file
combat.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/combat.cpp.i
.PHONY : combat.cpp.i

combat.s: combat.cpp.s
.PHONY : combat.s

# target to generate assembly for a file
combat.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/combat.cpp.s
.PHONY : combat.cpp.s

commands.o: commands.cpp.o
.PHONY : commands.o

# target to build an object file
commands.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/commands.cpp.o
.PHONY : commands.cpp.o

commands.i: commands.cpp.i
.PHONY : commands.i

# target to preprocess a source file
commands.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/commands.cpp.i
.PHONY : commands.cpp.i

commands.s: commands.cpp.s
.PHONY : commands.s

# target to generate assembly for a file
commands.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/commands.cpp.s
.PHONY : commands.cpp.s

condition.o: condition.cpp.o
.PHONY : condition.o

# target to build an object file
condition.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/condition.cpp.o
.PHONY : condition.cpp.o

condition.i: condition.cpp.i
.PHONY : condition.i

# target to preprocess a source file
condition.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/condition.cpp.i
.PHONY : condition.cpp.i

condition.s: condition.cpp.s
.PHONY : condition.s

# target to generate assembly for a file
condition.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/condition.cpp.s
.PHONY : condition.cpp.s

configmanager.o: configmanager.cpp.o
.PHONY : configmanager.o

# target to build an object file
configmanager.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/configmanager.cpp.o
.PHONY : configmanager.cpp.o

configmanager.i: configmanager.cpp.i
.PHONY : configmanager.i

# target to preprocess a source file
configmanager.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/configmanager.cpp.i
.PHONY : configmanager.cpp.i

configmanager.s: configmanager.cpp.s
.PHONY : configmanager.s

# target to generate assembly for a file
configmanager.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/configmanager.cpp.s
.PHONY : configmanager.cpp.s

connection.o: connection.cpp.o
.PHONY : connection.o

# target to build an object file
connection.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/connection.cpp.o
.PHONY : connection.cpp.o

connection.i: connection.cpp.i
.PHONY : connection.i

# target to preprocess a source file
connection.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/connection.cpp.i
.PHONY : connection.cpp.i

connection.s: connection.cpp.s
.PHONY : connection.s

# target to generate assembly for a file
connection.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/connection.cpp.s
.PHONY : connection.cpp.s

container.o: container.cpp.o
.PHONY : container.o

# target to build an object file
container.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/container.cpp.o
.PHONY : container.cpp.o

container.i: container.cpp.i
.PHONY : container.i

# target to preprocess a source file
container.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/container.cpp.i
.PHONY : container.cpp.i

container.s: container.cpp.s
.PHONY : container.s

# target to generate assembly for a file
container.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/container.cpp.s
.PHONY : container.cpp.s

creature.o: creature.cpp.o
.PHONY : creature.o

# target to build an object file
creature.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creature.cpp.o
.PHONY : creature.cpp.o

creature.i: creature.cpp.i
.PHONY : creature.i

# target to preprocess a source file
creature.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creature.cpp.i
.PHONY : creature.cpp.i

creature.s: creature.cpp.s
.PHONY : creature.s

# target to generate assembly for a file
creature.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creature.cpp.s
.PHONY : creature.cpp.s

creatureevent.o: creatureevent.cpp.o
.PHONY : creatureevent.o

# target to build an object file
creatureevent.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creatureevent.cpp.o
.PHONY : creatureevent.cpp.o

creatureevent.i: creatureevent.cpp.i
.PHONY : creatureevent.i

# target to preprocess a source file
creatureevent.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creatureevent.cpp.i
.PHONY : creatureevent.cpp.i

creatureevent.s: creatureevent.cpp.s
.PHONY : creatureevent.s

# target to generate assembly for a file
creatureevent.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/creatureevent.cpp.s
.PHONY : creatureevent.cpp.s

cylinder.o: cylinder.cpp.o
.PHONY : cylinder.o

# target to build an object file
cylinder.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/cylinder.cpp.o
.PHONY : cylinder.cpp.o

cylinder.i: cylinder.cpp.i
.PHONY : cylinder.i

# target to preprocess a source file
cylinder.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/cylinder.cpp.i
.PHONY : cylinder.cpp.i

cylinder.s: cylinder.cpp.s
.PHONY : cylinder.s

# target to generate assembly for a file
cylinder.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/cylinder.cpp.s
.PHONY : cylinder.cpp.s

database.o: database.cpp.o
.PHONY : database.o

# target to build an object file
database.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/database.cpp.o
.PHONY : database.cpp.o

database.i: database.cpp.i
.PHONY : database.i

# target to preprocess a source file
database.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/database.cpp.i
.PHONY : database.cpp.i

database.s: database.cpp.s
.PHONY : database.s

# target to generate assembly for a file
database.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/database.cpp.s
.PHONY : database.cpp.s

databasemanager.o: databasemanager.cpp.o
.PHONY : databasemanager.o

# target to build an object file
databasemanager.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasemanager.cpp.o
.PHONY : databasemanager.cpp.o

databasemanager.i: databasemanager.cpp.i
.PHONY : databasemanager.i

# target to preprocess a source file
databasemanager.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasemanager.cpp.i
.PHONY : databasemanager.cpp.i

databasemanager.s: databasemanager.cpp.s
.PHONY : databasemanager.s

# target to generate assembly for a file
databasemanager.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasemanager.cpp.s
.PHONY : databasemanager.cpp.s

databasetasks.o: databasetasks.cpp.o
.PHONY : databasetasks.o

# target to build an object file
databasetasks.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasetasks.cpp.o
.PHONY : databasetasks.cpp.o

databasetasks.i: databasetasks.cpp.i
.PHONY : databasetasks.i

# target to preprocess a source file
databasetasks.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasetasks.cpp.i
.PHONY : databasetasks.cpp.i

databasetasks.s: databasetasks.cpp.s
.PHONY : databasetasks.s

# target to generate assembly for a file
databasetasks.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/databasetasks.cpp.s
.PHONY : databasetasks.cpp.s

depotchest.o: depotchest.cpp.o
.PHONY : depotchest.o

# target to build an object file
depotchest.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotchest.cpp.o
.PHONY : depotchest.cpp.o

depotchest.i: depotchest.cpp.i
.PHONY : depotchest.i

# target to preprocess a source file
depotchest.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotchest.cpp.i
.PHONY : depotchest.cpp.i

depotchest.s: depotchest.cpp.s
.PHONY : depotchest.s

# target to generate assembly for a file
depotchest.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotchest.cpp.s
.PHONY : depotchest.cpp.s

depotlocker.o: depotlocker.cpp.o
.PHONY : depotlocker.o

# target to build an object file
depotlocker.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotlocker.cpp.o
.PHONY : depotlocker.cpp.o

depotlocker.i: depotlocker.cpp.i
.PHONY : depotlocker.i

# target to preprocess a source file
depotlocker.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotlocker.cpp.i
.PHONY : depotlocker.cpp.i

depotlocker.s: depotlocker.cpp.s
.PHONY : depotlocker.s

# target to generate assembly for a file
depotlocker.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/depotlocker.cpp.s
.PHONY : depotlocker.cpp.s

events.o: events.cpp.o
.PHONY : events.o

# target to build an object file
events.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/events.cpp.o
.PHONY : events.cpp.o

events.i: events.cpp.i
.PHONY : events.i

# target to preprocess a source file
events.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/events.cpp.i
.PHONY : events.cpp.i

events.s: events.cpp.s
.PHONY : events.s

# target to generate assembly for a file
events.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/events.cpp.s
.PHONY : events.cpp.s

fileloader.o: fileloader.cpp.o
.PHONY : fileloader.o

# target to build an object file
fileloader.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/fileloader.cpp.o
.PHONY : fileloader.cpp.o

fileloader.i: fileloader.cpp.i
.PHONY : fileloader.i

# target to preprocess a source file
fileloader.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/fileloader.cpp.i
.PHONY : fileloader.cpp.i

fileloader.s: fileloader.cpp.s
.PHONY : fileloader.s

# target to generate assembly for a file
fileloader.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/fileloader.cpp.s
.PHONY : fileloader.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/game.cpp.s
.PHONY : game.cpp.s

globalevent.o: globalevent.cpp.o
.PHONY : globalevent.o

# target to build an object file
globalevent.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/globalevent.cpp.o
.PHONY : globalevent.cpp.o

globalevent.i: globalevent.cpp.i
.PHONY : globalevent.i

# target to preprocess a source file
globalevent.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/globalevent.cpp.i
.PHONY : globalevent.cpp.i

globalevent.s: globalevent.cpp.s
.PHONY : globalevent.s

# target to generate assembly for a file
globalevent.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/globalevent.cpp.s
.PHONY : globalevent.cpp.s

groups.o: groups.cpp.o
.PHONY : groups.o

# target to build an object file
groups.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/groups.cpp.o
.PHONY : groups.cpp.o

groups.i: groups.cpp.i
.PHONY : groups.i

# target to preprocess a source file
groups.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/groups.cpp.i
.PHONY : groups.cpp.i

groups.s: groups.cpp.s
.PHONY : groups.s

# target to generate assembly for a file
groups.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/groups.cpp.s
.PHONY : groups.cpp.s

guild.o: guild.cpp.o
.PHONY : guild.o

# target to build an object file
guild.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/guild.cpp.o
.PHONY : guild.cpp.o

guild.i: guild.cpp.i
.PHONY : guild.i

# target to preprocess a source file
guild.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/guild.cpp.i
.PHONY : guild.cpp.i

guild.s: guild.cpp.s
.PHONY : guild.s

# target to generate assembly for a file
guild.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/guild.cpp.s
.PHONY : guild.cpp.s

house.o: house.cpp.o
.PHONY : house.o

# target to build an object file
house.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/house.cpp.o
.PHONY : house.cpp.o

house.i: house.cpp.i
.PHONY : house.i

# target to preprocess a source file
house.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/house.cpp.i
.PHONY : house.cpp.i

house.s: house.cpp.s
.PHONY : house.s

# target to generate assembly for a file
house.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/house.cpp.s
.PHONY : house.cpp.s

housetile.o: housetile.cpp.o
.PHONY : housetile.o

# target to build an object file
housetile.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/housetile.cpp.o
.PHONY : housetile.cpp.o

housetile.i: housetile.cpp.i
.PHONY : housetile.i

# target to preprocess a source file
housetile.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/housetile.cpp.i
.PHONY : housetile.cpp.i

housetile.s: housetile.cpp.s
.PHONY : housetile.s

# target to generate assembly for a file
housetile.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/housetile.cpp.s
.PHONY : housetile.cpp.s

inbox.o: inbox.cpp.o
.PHONY : inbox.o

# target to build an object file
inbox.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/inbox.cpp.o
.PHONY : inbox.cpp.o

inbox.i: inbox.cpp.i
.PHONY : inbox.i

# target to preprocess a source file
inbox.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/inbox.cpp.i
.PHONY : inbox.cpp.i

inbox.s: inbox.cpp.s
.PHONY : inbox.s

# target to generate assembly for a file
inbox.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/inbox.cpp.s
.PHONY : inbox.cpp.s

ioguild.o: ioguild.cpp.o
.PHONY : ioguild.o

# target to build an object file
ioguild.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ioguild.cpp.o
.PHONY : ioguild.cpp.o

ioguild.i: ioguild.cpp.i
.PHONY : ioguild.i

# target to preprocess a source file
ioguild.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ioguild.cpp.i
.PHONY : ioguild.cpp.i

ioguild.s: ioguild.cpp.s
.PHONY : ioguild.s

# target to generate assembly for a file
ioguild.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/ioguild.cpp.s
.PHONY : ioguild.cpp.s

iologindata.o: iologindata.cpp.o
.PHONY : iologindata.o

# target to build an object file
iologindata.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iologindata.cpp.o
.PHONY : iologindata.cpp.o

iologindata.i: iologindata.cpp.i
.PHONY : iologindata.i

# target to preprocess a source file
iologindata.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iologindata.cpp.i
.PHONY : iologindata.cpp.i

iologindata.s: iologindata.cpp.s
.PHONY : iologindata.s

# target to generate assembly for a file
iologindata.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iologindata.cpp.s
.PHONY : iologindata.cpp.s

iomap.o: iomap.cpp.o
.PHONY : iomap.o

# target to build an object file
iomap.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomap.cpp.o
.PHONY : iomap.cpp.o

iomap.i: iomap.cpp.i
.PHONY : iomap.i

# target to preprocess a source file
iomap.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomap.cpp.i
.PHONY : iomap.cpp.i

iomap.s: iomap.cpp.s
.PHONY : iomap.s

# target to generate assembly for a file
iomap.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomap.cpp.s
.PHONY : iomap.cpp.s

iomapserialize.o: iomapserialize.cpp.o
.PHONY : iomapserialize.o

# target to build an object file
iomapserialize.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomapserialize.cpp.o
.PHONY : iomapserialize.cpp.o

iomapserialize.i: iomapserialize.cpp.i
.PHONY : iomapserialize.i

# target to preprocess a source file
iomapserialize.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomapserialize.cpp.i
.PHONY : iomapserialize.cpp.i

iomapserialize.s: iomapserialize.cpp.s
.PHONY : iomapserialize.s

# target to generate assembly for a file
iomapserialize.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomapserialize.cpp.s
.PHONY : iomapserialize.cpp.s

iomarket.o: iomarket.cpp.o
.PHONY : iomarket.o

# target to build an object file
iomarket.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomarket.cpp.o
.PHONY : iomarket.cpp.o

iomarket.i: iomarket.cpp.i
.PHONY : iomarket.i

# target to preprocess a source file
iomarket.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomarket.cpp.i
.PHONY : iomarket.cpp.i

iomarket.s: iomarket.cpp.s
.PHONY : iomarket.s

# target to generate assembly for a file
iomarket.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/iomarket.cpp.s
.PHONY : iomarket.cpp.s

item.o: item.cpp.o
.PHONY : item.o

# target to build an object file
item.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/item.cpp.o
.PHONY : item.cpp.o

item.i: item.cpp.i
.PHONY : item.i

# target to preprocess a source file
item.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/item.cpp.i
.PHONY : item.cpp.i

item.s: item.cpp.s
.PHONY : item.s

# target to generate assembly for a file
item.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/item.cpp.s
.PHONY : item.cpp.s

items.o: items.cpp.o
.PHONY : items.o

# target to build an object file
items.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/items.cpp.o
.PHONY : items.cpp.o

items.i: items.cpp.i
.PHONY : items.i

# target to preprocess a source file
items.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/items.cpp.i
.PHONY : items.cpp.i

items.s: items.cpp.s
.PHONY : items.s

# target to generate assembly for a file
items.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/items.cpp.s
.PHONY : items.cpp.s

luascript.o: luascript.cpp.o
.PHONY : luascript.o

# target to build an object file
luascript.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/luascript.cpp.o
.PHONY : luascript.cpp.o

luascript.i: luascript.cpp.i
.PHONY : luascript.i

# target to preprocess a source file
luascript.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/luascript.cpp.i
.PHONY : luascript.cpp.i

luascript.s: luascript.cpp.s
.PHONY : luascript.s

# target to generate assembly for a file
luascript.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/luascript.cpp.s
.PHONY : luascript.cpp.s

mailbox.o: mailbox.cpp.o
.PHONY : mailbox.o

# target to build an object file
mailbox.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mailbox.cpp.o
.PHONY : mailbox.cpp.o

mailbox.i: mailbox.cpp.i
.PHONY : mailbox.i

# target to preprocess a source file
mailbox.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mailbox.cpp.i
.PHONY : mailbox.cpp.i

mailbox.s: mailbox.cpp.s
.PHONY : mailbox.s

# target to generate assembly for a file
mailbox.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mailbox.cpp.s
.PHONY : mailbox.cpp.s

map.o: map.cpp.o
.PHONY : map.o

# target to build an object file
map.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/map.cpp.o
.PHONY : map.cpp.o

map.i: map.cpp.i
.PHONY : map.i

# target to preprocess a source file
map.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/map.cpp.i
.PHONY : map.cpp.i

map.s: map.cpp.s
.PHONY : map.s

# target to generate assembly for a file
map.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/map.cpp.s
.PHONY : map.cpp.s

modules.o: modules.cpp.o
.PHONY : modules.o

# target to build an object file
modules.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/modules.cpp.o
.PHONY : modules.cpp.o

modules.i: modules.cpp.i
.PHONY : modules.i

# target to preprocess a source file
modules.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/modules.cpp.i
.PHONY : modules.cpp.i

modules.s: modules.cpp.s
.PHONY : modules.s

# target to generate assembly for a file
modules.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/modules.cpp.s
.PHONY : modules.cpp.s

monster.o: monster.cpp.o
.PHONY : monster.o

# target to build an object file
monster.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monster.cpp.o
.PHONY : monster.cpp.o

monster.i: monster.cpp.i
.PHONY : monster.i

# target to preprocess a source file
monster.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monster.cpp.i
.PHONY : monster.cpp.i

monster.s: monster.cpp.s
.PHONY : monster.s

# target to generate assembly for a file
monster.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monster.cpp.s
.PHONY : monster.cpp.s

monsters.o: monsters.cpp.o
.PHONY : monsters.o

# target to build an object file
monsters.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monsters.cpp.o
.PHONY : monsters.cpp.o

monsters.i: monsters.cpp.i
.PHONY : monsters.i

# target to preprocess a source file
monsters.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monsters.cpp.i
.PHONY : monsters.cpp.i

monsters.s: monsters.cpp.s
.PHONY : monsters.s

# target to generate assembly for a file
monsters.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/monsters.cpp.s
.PHONY : monsters.cpp.s

mounts.o: mounts.cpp.o
.PHONY : mounts.o

# target to build an object file
mounts.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mounts.cpp.o
.PHONY : mounts.cpp.o

mounts.i: mounts.cpp.i
.PHONY : mounts.i

# target to preprocess a source file
mounts.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mounts.cpp.i
.PHONY : mounts.cpp.i

mounts.s: mounts.cpp.s
.PHONY : mounts.s

# target to generate assembly for a file
mounts.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/mounts.cpp.s
.PHONY : mounts.cpp.s

movement.o: movement.cpp.o
.PHONY : movement.o

# target to build an object file
movement.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/movement.cpp.o
.PHONY : movement.cpp.o

movement.i: movement.cpp.i
.PHONY : movement.i

# target to preprocess a source file
movement.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/movement.cpp.i
.PHONY : movement.cpp.i

movement.s: movement.cpp.s
.PHONY : movement.s

# target to generate assembly for a file
movement.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/movement.cpp.s
.PHONY : movement.cpp.s

networkmessage.o: networkmessage.cpp.o
.PHONY : networkmessage.o

# target to build an object file
networkmessage.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/networkmessage.cpp.o
.PHONY : networkmessage.cpp.o

networkmessage.i: networkmessage.cpp.i
.PHONY : networkmessage.i

# target to preprocess a source file
networkmessage.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/networkmessage.cpp.i
.PHONY : networkmessage.cpp.i

networkmessage.s: networkmessage.cpp.s
.PHONY : networkmessage.s

# target to generate assembly for a file
networkmessage.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/networkmessage.cpp.s
.PHONY : networkmessage.cpp.s

npc.o: npc.cpp.o
.PHONY : npc.o

# target to build an object file
npc.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/npc.cpp.o
.PHONY : npc.cpp.o

npc.i: npc.cpp.i
.PHONY : npc.i

# target to preprocess a source file
npc.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/npc.cpp.i
.PHONY : npc.cpp.i

npc.s: npc.cpp.s
.PHONY : npc.s

# target to generate assembly for a file
npc.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/npc.cpp.s
.PHONY : npc.cpp.s

otpch.o: otpch.cpp.o
.PHONY : otpch.o

# target to build an object file
otpch.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otpch.cpp.o
.PHONY : otpch.cpp.o

otpch.i: otpch.cpp.i
.PHONY : otpch.i

# target to preprocess a source file
otpch.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otpch.cpp.i
.PHONY : otpch.cpp.i

otpch.s: otpch.cpp.s
.PHONY : otpch.s

# target to generate assembly for a file
otpch.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otpch.cpp.s
.PHONY : otpch.cpp.s

otserv.o: otserv.cpp.o
.PHONY : otserv.o

# target to build an object file
otserv.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otserv.cpp.o
.PHONY : otserv.cpp.o

otserv.i: otserv.cpp.i
.PHONY : otserv.i

# target to preprocess a source file
otserv.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otserv.cpp.i
.PHONY : otserv.cpp.i

otserv.s: otserv.cpp.s
.PHONY : otserv.s

# target to generate assembly for a file
otserv.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/otserv.cpp.s
.PHONY : otserv.cpp.s

outfit.o: outfit.cpp.o
.PHONY : outfit.o

# target to build an object file
outfit.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outfit.cpp.o
.PHONY : outfit.cpp.o

outfit.i: outfit.cpp.i
.PHONY : outfit.i

# target to preprocess a source file
outfit.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outfit.cpp.i
.PHONY : outfit.cpp.i

outfit.s: outfit.cpp.s
.PHONY : outfit.s

# target to generate assembly for a file
outfit.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outfit.cpp.s
.PHONY : outfit.cpp.s

outputmessage.o: outputmessage.cpp.o
.PHONY : outputmessage.o

# target to build an object file
outputmessage.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outputmessage.cpp.o
.PHONY : outputmessage.cpp.o

outputmessage.i: outputmessage.cpp.i
.PHONY : outputmessage.i

# target to preprocess a source file
outputmessage.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outputmessage.cpp.i
.PHONY : outputmessage.cpp.i

outputmessage.s: outputmessage.cpp.s
.PHONY : outputmessage.s

# target to generate assembly for a file
outputmessage.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/outputmessage.cpp.s
.PHONY : outputmessage.cpp.s

party.o: party.cpp.o
.PHONY : party.o

# target to build an object file
party.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/party.cpp.o
.PHONY : party.cpp.o

party.i: party.cpp.i
.PHONY : party.i

# target to preprocess a source file
party.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/party.cpp.i
.PHONY : party.cpp.i

party.s: party.cpp.s
.PHONY : party.s

# target to generate assembly for a file
party.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/party.cpp.s
.PHONY : party.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/player.cpp.s
.PHONY : player.cpp.s

position.o: position.cpp.o
.PHONY : position.o

# target to build an object file
position.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/position.cpp.o
.PHONY : position.cpp.o

position.i: position.cpp.i
.PHONY : position.i

# target to preprocess a source file
position.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/position.cpp.i
.PHONY : position.cpp.i

position.s: position.cpp.s
.PHONY : position.s

# target to generate assembly for a file
position.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/position.cpp.s
.PHONY : position.cpp.s

protocol.o: protocol.cpp.o
.PHONY : protocol.o

# target to build an object file
protocol.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocol.cpp.o
.PHONY : protocol.cpp.o

protocol.i: protocol.cpp.i
.PHONY : protocol.i

# target to preprocess a source file
protocol.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocol.cpp.i
.PHONY : protocol.cpp.i

protocol.s: protocol.cpp.s
.PHONY : protocol.s

# target to generate assembly for a file
protocol.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocol.cpp.s
.PHONY : protocol.cpp.s

protocolflash.o: protocolflash.cpp.o
.PHONY : protocolflash.o

# target to build an object file
protocolflash.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolflash.cpp.o
.PHONY : protocolflash.cpp.o

protocolflash.i: protocolflash.cpp.i
.PHONY : protocolflash.i

# target to preprocess a source file
protocolflash.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolflash.cpp.i
.PHONY : protocolflash.cpp.i

protocolflash.s: protocolflash.cpp.s
.PHONY : protocolflash.s

# target to generate assembly for a file
protocolflash.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolflash.cpp.s
.PHONY : protocolflash.cpp.s

protocolgame.o: protocolgame.cpp.o
.PHONY : protocolgame.o

# target to build an object file
protocolgame.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgame.cpp.o
.PHONY : protocolgame.cpp.o

protocolgame.i: protocolgame.cpp.i
.PHONY : protocolgame.i

# target to preprocess a source file
protocolgame.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgame.cpp.i
.PHONY : protocolgame.cpp.i

protocolgame.s: protocolgame.cpp.s
.PHONY : protocolgame.s

# target to generate assembly for a file
protocolgame.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgame.cpp.s
.PHONY : protocolgame.cpp.s

protocolgamebase.o: protocolgamebase.cpp.o
.PHONY : protocolgamebase.o

# target to build an object file
protocolgamebase.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgamebase.cpp.o
.PHONY : protocolgamebase.cpp.o

protocolgamebase.i: protocolgamebase.cpp.i
.PHONY : protocolgamebase.i

# target to preprocess a source file
protocolgamebase.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgamebase.cpp.i
.PHONY : protocolgamebase.cpp.i

protocolgamebase.s: protocolgamebase.cpp.s
.PHONY : protocolgamebase.s

# target to generate assembly for a file
protocolgamebase.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolgamebase.cpp.s
.PHONY : protocolgamebase.cpp.s

protocollogin.o: protocollogin.cpp.o
.PHONY : protocollogin.o

# target to build an object file
protocollogin.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocollogin.cpp.o
.PHONY : protocollogin.cpp.o

protocollogin.i: protocollogin.cpp.i
.PHONY : protocollogin.i

# target to preprocess a source file
protocollogin.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocollogin.cpp.i
.PHONY : protocollogin.cpp.i

protocollogin.s: protocollogin.cpp.s
.PHONY : protocollogin.s

# target to generate assembly for a file
protocollogin.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocollogin.cpp.s
.PHONY : protocollogin.cpp.s

protocolold.o: protocolold.cpp.o
.PHONY : protocolold.o

# target to build an object file
protocolold.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolold.cpp.o
.PHONY : protocolold.cpp.o

protocolold.i: protocolold.cpp.i
.PHONY : protocolold.i

# target to preprocess a source file
protocolold.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolold.cpp.i
.PHONY : protocolold.cpp.i

protocolold.s: protocolold.cpp.s
.PHONY : protocolold.s

# target to generate assembly for a file
protocolold.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolold.cpp.s
.PHONY : protocolold.cpp.s

protocolspectator.o: protocolspectator.cpp.o
.PHONY : protocolspectator.o

# target to build an object file
protocolspectator.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolspectator.cpp.o
.PHONY : protocolspectator.cpp.o

protocolspectator.i: protocolspectator.cpp.i
.PHONY : protocolspectator.i

# target to preprocess a source file
protocolspectator.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolspectator.cpp.i
.PHONY : protocolspectator.cpp.i

protocolspectator.s: protocolspectator.cpp.s
.PHONY : protocolspectator.s

# target to generate assembly for a file
protocolspectator.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolspectator.cpp.s
.PHONY : protocolspectator.cpp.s

protocolstatus.o: protocolstatus.cpp.o
.PHONY : protocolstatus.o

# target to build an object file
protocolstatus.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolstatus.cpp.o
.PHONY : protocolstatus.cpp.o

protocolstatus.i: protocolstatus.cpp.i
.PHONY : protocolstatus.i

# target to preprocess a source file
protocolstatus.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolstatus.cpp.i
.PHONY : protocolstatus.cpp.i

protocolstatus.s: protocolstatus.cpp.s
.PHONY : protocolstatus.s

# target to generate assembly for a file
protocolstatus.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/protocolstatus.cpp.s
.PHONY : protocolstatus.cpp.s

quests.o: quests.cpp.o
.PHONY : quests.o

# target to build an object file
quests.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/quests.cpp.o
.PHONY : quests.cpp.o

quests.i: quests.cpp.i
.PHONY : quests.i

# target to preprocess a source file
quests.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/quests.cpp.i
.PHONY : quests.cpp.i

quests.s: quests.cpp.s
.PHONY : quests.s

# target to generate assembly for a file
quests.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/quests.cpp.s
.PHONY : quests.cpp.s

raids.o: raids.cpp.o
.PHONY : raids.o

# target to build an object file
raids.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/raids.cpp.o
.PHONY : raids.cpp.o

raids.i: raids.cpp.i
.PHONY : raids.i

# target to preprocess a source file
raids.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/raids.cpp.i
.PHONY : raids.cpp.i

raids.s: raids.cpp.s
.PHONY : raids.s

# target to generate assembly for a file
raids.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/raids.cpp.s
.PHONY : raids.cpp.s

reward.o: reward.cpp.o
.PHONY : reward.o

# target to build an object file
reward.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/reward.cpp.o
.PHONY : reward.cpp.o

reward.i: reward.cpp.i
.PHONY : reward.i

# target to preprocess a source file
reward.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/reward.cpp.i
.PHONY : reward.cpp.i

reward.s: reward.cpp.s
.PHONY : reward.s

# target to generate assembly for a file
reward.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/reward.cpp.s
.PHONY : reward.cpp.s

rewardchest.o: rewardchest.cpp.o
.PHONY : rewardchest.o

# target to build an object file
rewardchest.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rewardchest.cpp.o
.PHONY : rewardchest.cpp.o

rewardchest.i: rewardchest.cpp.i
.PHONY : rewardchest.i

# target to preprocess a source file
rewardchest.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rewardchest.cpp.i
.PHONY : rewardchest.cpp.i

rewardchest.s: rewardchest.cpp.s
.PHONY : rewardchest.s

# target to generate assembly for a file
rewardchest.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rewardchest.cpp.s
.PHONY : rewardchest.cpp.s

rsa.o: rsa.cpp.o
.PHONY : rsa.o

# target to build an object file
rsa.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rsa.cpp.o
.PHONY : rsa.cpp.o

rsa.i: rsa.cpp.i
.PHONY : rsa.i

# target to preprocess a source file
rsa.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rsa.cpp.i
.PHONY : rsa.cpp.i

rsa.s: rsa.cpp.s
.PHONY : rsa.s

# target to generate assembly for a file
rsa.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/rsa.cpp.s
.PHONY : rsa.cpp.s

scheduler.o: scheduler.cpp.o
.PHONY : scheduler.o

# target to build an object file
scheduler.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scheduler.cpp.o
.PHONY : scheduler.cpp.o

scheduler.i: scheduler.cpp.i
.PHONY : scheduler.i

# target to preprocess a source file
scheduler.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scheduler.cpp.i
.PHONY : scheduler.cpp.i

scheduler.s: scheduler.cpp.s
.PHONY : scheduler.s

# target to generate assembly for a file
scheduler.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scheduler.cpp.s
.PHONY : scheduler.cpp.s

scriptmanager.o: scriptmanager.cpp.o
.PHONY : scriptmanager.o

# target to build an object file
scriptmanager.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scriptmanager.cpp.o
.PHONY : scriptmanager.cpp.o

scriptmanager.i: scriptmanager.cpp.i
.PHONY : scriptmanager.i

# target to preprocess a source file
scriptmanager.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scriptmanager.cpp.i
.PHONY : scriptmanager.cpp.i

scriptmanager.s: scriptmanager.cpp.s
.PHONY : scriptmanager.s

# target to generate assembly for a file
scriptmanager.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/scriptmanager.cpp.s
.PHONY : scriptmanager.cpp.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/server.cpp.s
.PHONY : server.cpp.s

signals.o: signals.cpp.o
.PHONY : signals.o

# target to build an object file
signals.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/signals.cpp.o
.PHONY : signals.cpp.o

signals.i: signals.cpp.i
.PHONY : signals.i

# target to preprocess a source file
signals.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/signals.cpp.i
.PHONY : signals.cpp.i

signals.s: signals.cpp.s
.PHONY : signals.s

# target to generate assembly for a file
signals.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/signals.cpp.s
.PHONY : signals.cpp.s

spawn.o: spawn.cpp.o
.PHONY : spawn.o

# target to build an object file
spawn.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spawn.cpp.o
.PHONY : spawn.cpp.o

spawn.i: spawn.cpp.i
.PHONY : spawn.i

# target to preprocess a source file
spawn.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spawn.cpp.i
.PHONY : spawn.cpp.i

spawn.s: spawn.cpp.s
.PHONY : spawn.s

# target to generate assembly for a file
spawn.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spawn.cpp.s
.PHONY : spawn.cpp.s

spells.o: spells.cpp.o
.PHONY : spells.o

# target to build an object file
spells.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spells.cpp.o
.PHONY : spells.cpp.o

spells.i: spells.cpp.i
.PHONY : spells.i

# target to preprocess a source file
spells.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spells.cpp.i
.PHONY : spells.cpp.i

spells.s: spells.cpp.s
.PHONY : spells.s

# target to generate assembly for a file
spells.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/spells.cpp.s
.PHONY : spells.cpp.s

talkaction.o: talkaction.cpp.o
.PHONY : talkaction.o

# target to build an object file
talkaction.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/talkaction.cpp.o
.PHONY : talkaction.cpp.o

talkaction.i: talkaction.cpp.i
.PHONY : talkaction.i

# target to preprocess a source file
talkaction.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/talkaction.cpp.i
.PHONY : talkaction.cpp.i

talkaction.s: talkaction.cpp.s
.PHONY : talkaction.s

# target to generate assembly for a file
talkaction.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/talkaction.cpp.s
.PHONY : talkaction.cpp.s

tasks.o: tasks.cpp.o
.PHONY : tasks.o

# target to build an object file
tasks.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tasks.cpp.o
.PHONY : tasks.cpp.o

tasks.i: tasks.cpp.i
.PHONY : tasks.i

# target to preprocess a source file
tasks.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tasks.cpp.i
.PHONY : tasks.cpp.i

tasks.s: tasks.cpp.s
.PHONY : tasks.s

# target to generate assembly for a file
tasks.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tasks.cpp.s
.PHONY : tasks.cpp.s

teleport.o: teleport.cpp.o
.PHONY : teleport.o

# target to build an object file
teleport.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/teleport.cpp.o
.PHONY : teleport.cpp.o

teleport.i: teleport.cpp.i
.PHONY : teleport.i

# target to preprocess a source file
teleport.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/teleport.cpp.i
.PHONY : teleport.cpp.i

teleport.s: teleport.cpp.s
.PHONY : teleport.s

# target to generate assembly for a file
teleport.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/teleport.cpp.s
.PHONY : teleport.cpp.s

thing.o: thing.cpp.o
.PHONY : thing.o

# target to build an object file
thing.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/thing.cpp.o
.PHONY : thing.cpp.o

thing.i: thing.cpp.i
.PHONY : thing.i

# target to preprocess a source file
thing.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/thing.cpp.i
.PHONY : thing.cpp.i

thing.s: thing.cpp.s
.PHONY : thing.s

# target to generate assembly for a file
thing.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/thing.cpp.s
.PHONY : thing.cpp.s

tile.o: tile.cpp.o
.PHONY : tile.o

# target to build an object file
tile.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tile.cpp.o
.PHONY : tile.cpp.o

tile.i: tile.cpp.i
.PHONY : tile.i

# target to preprocess a source file
tile.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tile.cpp.i
.PHONY : tile.cpp.i

tile.s: tile.cpp.s
.PHONY : tile.s

# target to generate assembly for a file
tile.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tile.cpp.s
.PHONY : tile.cpp.s

tools.o: tools.cpp.o
.PHONY : tools.o

# target to build an object file
tools.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tools.cpp.o
.PHONY : tools.cpp.o

tools.i: tools.cpp.i
.PHONY : tools.i

# target to preprocess a source file
tools.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tools.cpp.i
.PHONY : tools.cpp.i

tools.s: tools.cpp.s
.PHONY : tools.s

# target to generate assembly for a file
tools.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/tools.cpp.s
.PHONY : tools.cpp.s

trashholder.o: trashholder.cpp.o
.PHONY : trashholder.o

# target to build an object file
trashholder.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/trashholder.cpp.o
.PHONY : trashholder.cpp.o

trashholder.i: trashholder.cpp.i
.PHONY : trashholder.i

# target to preprocess a source file
trashholder.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/trashholder.cpp.i
.PHONY : trashholder.cpp.i

trashholder.s: trashholder.cpp.s
.PHONY : trashholder.s

# target to generate assembly for a file
trashholder.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/trashholder.cpp.s
.PHONY : trashholder.cpp.s

vocation.o: vocation.cpp.o
.PHONY : vocation.o

# target to build an object file
vocation.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/vocation.cpp.o
.PHONY : vocation.cpp.o

vocation.i: vocation.cpp.i
.PHONY : vocation.i

# target to preprocess a source file
vocation.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/vocation.cpp.i
.PHONY : vocation.cpp.i

vocation.s: vocation.cpp.s
.PHONY : vocation.s

# target to generate assembly for a file
vocation.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/vocation.cpp.s
.PHONY : vocation.cpp.s

waitlist.o: waitlist.cpp.o
.PHONY : waitlist.o

# target to build an object file
waitlist.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/waitlist.cpp.o
.PHONY : waitlist.cpp.o

waitlist.i: waitlist.cpp.i
.PHONY : waitlist.i

# target to preprocess a source file
waitlist.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/waitlist.cpp.i
.PHONY : waitlist.cpp.i

waitlist.s: waitlist.cpp.s
.PHONY : waitlist.s

# target to generate assembly for a file
waitlist.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/waitlist.cpp.s
.PHONY : waitlist.cpp.s

weapons.o: weapons.cpp.o
.PHONY : weapons.o

# target to build an object file
weapons.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/weapons.cpp.o
.PHONY : weapons.cpp.o

weapons.i: weapons.cpp.i
.PHONY : weapons.i

# target to preprocess a source file
weapons.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/weapons.cpp.i
.PHONY : weapons.cpp.i

weapons.s: weapons.cpp.s
.PHONY : weapons.s

# target to generate assembly for a file
weapons.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/weapons.cpp.s
.PHONY : weapons.cpp.s

wildcardtree.o: wildcardtree.cpp.o
.PHONY : wildcardtree.o

# target to build an object file
wildcardtree.cpp.o:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/wildcardtree.cpp.o
.PHONY : wildcardtree.cpp.o

wildcardtree.i: wildcardtree.cpp.i
.PHONY : wildcardtree.i

# target to preprocess a source file
wildcardtree.cpp.i:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/wildcardtree.cpp.i
.PHONY : wildcardtree.cpp.i

wildcardtree.s: wildcardtree.cpp.s
.PHONY : wildcardtree.s

# target to generate assembly for a file
wildcardtree.cpp.s:
	$(MAKE) -f CMakeFiles/tfs.dir/build.make CMakeFiles/tfs.dir/wildcardtree.cpp.s
.PHONY : wildcardtree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tfs"
	@echo "... actions.o"
	@echo "... actions.i"
	@echo "... actions.s"
	@echo "... ban.o"
	@echo "... ban.i"
	@echo "... ban.s"
	@echo "... baseevents.o"
	@echo "... baseevents.i"
	@echo "... baseevents.s"
	@echo "... bed.o"
	@echo "... bed.i"
	@echo "... bed.s"
	@echo "... chat.o"
	@echo "... chat.i"
	@echo "... chat.s"
	@echo "... combat.o"
	@echo "... combat.i"
	@echo "... combat.s"
	@echo "... commands.o"
	@echo "... commands.i"
	@echo "... commands.s"
	@echo "... condition.o"
	@echo "... condition.i"
	@echo "... condition.s"
	@echo "... configmanager.o"
	@echo "... configmanager.i"
	@echo "... configmanager.s"
	@echo "... connection.o"
	@echo "... connection.i"
	@echo "... connection.s"
	@echo "... container.o"
	@echo "... container.i"
	@echo "... container.s"
	@echo "... creature.o"
	@echo "... creature.i"
	@echo "... creature.s"
	@echo "... creatureevent.o"
	@echo "... creatureevent.i"
	@echo "... creatureevent.s"
	@echo "... cylinder.o"
	@echo "... cylinder.i"
	@echo "... cylinder.s"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... databasemanager.o"
	@echo "... databasemanager.i"
	@echo "... databasemanager.s"
	@echo "... databasetasks.o"
	@echo "... databasetasks.i"
	@echo "... databasetasks.s"
	@echo "... depotchest.o"
	@echo "... depotchest.i"
	@echo "... depotchest.s"
	@echo "... depotlocker.o"
	@echo "... depotlocker.i"
	@echo "... depotlocker.s"
	@echo "... events.o"
	@echo "... events.i"
	@echo "... events.s"
	@echo "... fileloader.o"
	@echo "... fileloader.i"
	@echo "... fileloader.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... globalevent.o"
	@echo "... globalevent.i"
	@echo "... globalevent.s"
	@echo "... groups.o"
	@echo "... groups.i"
	@echo "... groups.s"
	@echo "... guild.o"
	@echo "... guild.i"
	@echo "... guild.s"
	@echo "... house.o"
	@echo "... house.i"
	@echo "... house.s"
	@echo "... housetile.o"
	@echo "... housetile.i"
	@echo "... housetile.s"
	@echo "... inbox.o"
	@echo "... inbox.i"
	@echo "... inbox.s"
	@echo "... ioguild.o"
	@echo "... ioguild.i"
	@echo "... ioguild.s"
	@echo "... iologindata.o"
	@echo "... iologindata.i"
	@echo "... iologindata.s"
	@echo "... iomap.o"
	@echo "... iomap.i"
	@echo "... iomap.s"
	@echo "... iomapserialize.o"
	@echo "... iomapserialize.i"
	@echo "... iomapserialize.s"
	@echo "... iomarket.o"
	@echo "... iomarket.i"
	@echo "... iomarket.s"
	@echo "... item.o"
	@echo "... item.i"
	@echo "... item.s"
	@echo "... items.o"
	@echo "... items.i"
	@echo "... items.s"
	@echo "... luascript.o"
	@echo "... luascript.i"
	@echo "... luascript.s"
	@echo "... mailbox.o"
	@echo "... mailbox.i"
	@echo "... mailbox.s"
	@echo "... map.o"
	@echo "... map.i"
	@echo "... map.s"
	@echo "... modules.o"
	@echo "... modules.i"
	@echo "... modules.s"
	@echo "... monster.o"
	@echo "... monster.i"
	@echo "... monster.s"
	@echo "... monsters.o"
	@echo "... monsters.i"
	@echo "... monsters.s"
	@echo "... mounts.o"
	@echo "... mounts.i"
	@echo "... mounts.s"
	@echo "... movement.o"
	@echo "... movement.i"
	@echo "... movement.s"
	@echo "... networkmessage.o"
	@echo "... networkmessage.i"
	@echo "... networkmessage.s"
	@echo "... npc.o"
	@echo "... npc.i"
	@echo "... npc.s"
	@echo "... otpch.o"
	@echo "... otpch.i"
	@echo "... otpch.s"
	@echo "... otserv.o"
	@echo "... otserv.i"
	@echo "... otserv.s"
	@echo "... outfit.o"
	@echo "... outfit.i"
	@echo "... outfit.s"
	@echo "... outputmessage.o"
	@echo "... outputmessage.i"
	@echo "... outputmessage.s"
	@echo "... party.o"
	@echo "... party.i"
	@echo "... party.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... position.o"
	@echo "... position.i"
	@echo "... position.s"
	@echo "... protocol.o"
	@echo "... protocol.i"
	@echo "... protocol.s"
	@echo "... protocolflash.o"
	@echo "... protocolflash.i"
	@echo "... protocolflash.s"
	@echo "... protocolgame.o"
	@echo "... protocolgame.i"
	@echo "... protocolgame.s"
	@echo "... protocolgamebase.o"
	@echo "... protocolgamebase.i"
	@echo "... protocolgamebase.s"
	@echo "... protocollogin.o"
	@echo "... protocollogin.i"
	@echo "... protocollogin.s"
	@echo "... protocolold.o"
	@echo "... protocolold.i"
	@echo "... protocolold.s"
	@echo "... protocolspectator.o"
	@echo "... protocolspectator.i"
	@echo "... protocolspectator.s"
	@echo "... protocolstatus.o"
	@echo "... protocolstatus.i"
	@echo "... protocolstatus.s"
	@echo "... quests.o"
	@echo "... quests.i"
	@echo "... quests.s"
	@echo "... raids.o"
	@echo "... raids.i"
	@echo "... raids.s"
	@echo "... reward.o"
	@echo "... reward.i"
	@echo "... reward.s"
	@echo "... rewardchest.o"
	@echo "... rewardchest.i"
	@echo "... rewardchest.s"
	@echo "... rsa.o"
	@echo "... rsa.i"
	@echo "... rsa.s"
	@echo "... scheduler.o"
	@echo "... scheduler.i"
	@echo "... scheduler.s"
	@echo "... scriptmanager.o"
	@echo "... scriptmanager.i"
	@echo "... scriptmanager.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... signals.o"
	@echo "... signals.i"
	@echo "... signals.s"
	@echo "... spawn.o"
	@echo "... spawn.i"
	@echo "... spawn.s"
	@echo "... spells.o"
	@echo "... spells.i"
	@echo "... spells.s"
	@echo "... talkaction.o"
	@echo "... talkaction.i"
	@echo "... talkaction.s"
	@echo "... tasks.o"
	@echo "... tasks.i"
	@echo "... tasks.s"
	@echo "... teleport.o"
	@echo "... teleport.i"
	@echo "... teleport.s"
	@echo "... thing.o"
	@echo "... thing.i"
	@echo "... thing.s"
	@echo "... tile.o"
	@echo "... tile.i"
	@echo "... tile.s"
	@echo "... tools.o"
	@echo "... tools.i"
	@echo "... tools.s"
	@echo "... trashholder.o"
	@echo "... trashholder.i"
	@echo "... trashholder.s"
	@echo "... vocation.o"
	@echo "... vocation.i"
	@echo "... vocation.s"
	@echo "... waitlist.o"
	@echo "... waitlist.i"
	@echo "... waitlist.s"
	@echo "... weapons.o"
	@echo "... weapons.i"
	@echo "... weapons.s"
	@echo "... wildcardtree.o"
	@echo "... wildcardtree.i"
	@echo "... wildcardtree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

